### PR TITLE
don't hard-code lld / mold, and copy all artifact types back to original folder

### PR DESCRIPTION
**Pull request by edgimar**
see commits for details

### CODE REVIEW

**Review by asaaki — COMMENTED** [review]
Hi and thank you for your contribution.

I hope the changes will address your use cases you have.

One tiny nit in the config part, but happy to merge and release a new version soon.

**Comment by asaaki** [comment]
I just noticed that it copies way too many files back than I wanted.

The additional artifacts should be probably gated behind a flag/config, so users can opt-in.

Would you want to implement the option? Or shall I do it after this PR?

**Comment by edgimar** [comment]
> I just noticed that it copies way too many files back than I wanted.

I agree that it can end up copying a lot (especially the `lib` and `rlib` artifacts).  I have updated the PR to include only `bin`, `dylib` and `cdylib` by default.  It would be nice to also allow this to be overridden by a config option that explicitly specifies all of the kinds of artifacts to include (if the config option is missing, the default is used, otherwise whatever is in the config option is used).  It also might make sense to provide a config setting where the user can (optionally) provide a regexp to match artifact filenames that should be copied (this would be checked after the initial artifact-kind filter has been applied). Does that sound reasonable?

> Would you want to implement the option? Or shall I do it after this PR?

I could implement it, but might not get to it right away.  I'm fine with taking either path, but probably the new PR can be merged in any case.

**Comment by edgimar** [comment]
> These lines can also be commented, since we should stick to defaults or user overrides (for example via `~/.cargo/config.toml`).

PR is now updated accordingly.

**Pull request merged**
